version: "2.3"
services:
    cosmos:
        image: uwcosmos/cosmos:standalone
        runtime: nvidia
        ipc: host
        volumes:
            - .:/cosmos/
            - ${INPUT_DIR}:/input/
            - ${OUTPUT_DIR}:/output/ 
        command: "python run.py /input  -w torch_model/model_weights.pth -t 4 -o /output/ -d ${DEVICE} -k"

    cosmos_postgres:
        image: postgres:10.5-alpine
        environment:
            - POSTGRES_DB=cosmos
